/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package module1;

import java.util.Set;
import java.awt.Font;

/**
 *
 * @author asus
 */
public class Front extends javax.swing.JFrame {
    
    public Front() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fd = new javax.swing.JLabel();
        attribute = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fds = new javax.swing.JTextField();
        cfd = new javax.swing.JButton();
        ca = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        check3 = new javax.swing.JButton();
        checkb = new javax.swing.JButton();
        ck = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        space1 = new javax.swing.JTextArea();
        sk = new javax.swing.JButton();
        bdeco = new javax.swing.JButton();
        Deco2 = new javax.swing.JButton();
        check2 = new javax.swing.JButton();
        Deco3 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        space2 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        space3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 5));

        fd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fd.setForeground(new java.awt.Color(255, 255, 255));
        fd.setText("FUNCTIONAL DEPENDENCIES :");

        attribute.setBackground(new java.awt.Color(204, 255, 255));
        attribute.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        attribute.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        attribute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attributeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ATTRIBUTES : ");

        fds.setBackground(new java.awt.Color(204, 255, 255));
        fds.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fds.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        fds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdsActionPerformed(evt);
            }
        });

        cfd.setBackground(new java.awt.Color(204, 0, 0));
        cfd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cfd.setForeground(new java.awt.Color(255, 255, 255));
        cfd.setText("Clear FD");
        cfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfdActionPerformed(evt);
            }
        });

        ca.setBackground(new java.awt.Color(204, 0, 0));
        ca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ca.setForeground(new java.awt.Color(255, 255, 255));
        ca.setText("Clear Attribute ");
        ca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caActionPerformed(evt);
            }
        });

        Submit.setBackground(new java.awt.Color(204, 0, 0));
        Submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Submit.setForeground(new java.awt.Color(255, 255, 255));
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        check3.setBackground(new java.awt.Color(0, 153, 76));
        check3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        check3.setForeground(new java.awt.Color(255, 255, 255));
        check3.setText("Check 3NF");
        check3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check3ActionPerformed(evt);
            }
        });

        checkb.setBackground(new java.awt.Color(0, 153, 76));
        checkb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkb.setForeground(new java.awt.Color(255, 255, 255));
        checkb.setText("Check BCNF");
        checkb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbActionPerformed(evt);
            }
        });

        ck.setBackground(new java.awt.Color(0, 153, 76));
        ck.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ck.setForeground(new java.awt.Color(255, 255, 255));
        ck.setText("Candidate Key");
        ck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckActionPerformed(evt);
            }
        });

        space1.setBackground(new java.awt.Color(204, 255, 255));
        space1.setColumns(20);
        space1.setLineWrap(true);
        space1.setRows(5);
        space1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        jScrollPane1.setViewportView(space1);

        sk.setBackground(new java.awt.Color(0, 153, 76));
        sk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sk.setForeground(new java.awt.Color(255, 255, 255));
        sk.setText("Super Key");
        sk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skActionPerformed(evt);
            }
        });

        bdeco.setBackground(new java.awt.Color(0, 153, 76));
        bdeco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bdeco.setForeground(new java.awt.Color(255, 255, 255));
        bdeco.setText("BCNF Decomposition");
        bdeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdecoActionPerformed(evt);
            }
        });

        Deco2.setBackground(new java.awt.Color(0, 153, 76));
        Deco2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Deco2.setForeground(new java.awt.Color(255, 255, 255));
        Deco2.setText("2NF Decomposition");
        Deco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deco2ActionPerformed(evt);
            }
        });

        check2.setBackground(new java.awt.Color(0, 153, 76));
        check2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        check2.setForeground(new java.awt.Color(255, 255, 255));
        check2.setText("Check 2NF");
        check2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check2ActionPerformed(evt);
            }
        });

        Deco3.setBackground(new java.awt.Color(0, 153, 76));
        Deco3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Deco3.setForeground(new java.awt.Color(255, 255, 255));
        Deco3.setText("3NF Decomposition");
        Deco3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deco3ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 76));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Closure");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        space2.setBackground(new java.awt.Color(204, 255, 255));
        space2.setColumns(20);
        space2.setLineWrap(true);
        space2.setRows(5);
        space2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        jScrollPane4.setViewportView(space2);

        space3.setBackground(new java.awt.Color(204, 255, 255));
        space3.setColumns(20);
        space3.setRows(5);
        space3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        jScrollPane5.setViewportView(space3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fd))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ca, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(cfd, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fds, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attribute, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(sk, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(check2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(check3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Deco2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Deco3))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(ck)
                .addGap(290, 290, 290)
                .addComponent(checkb, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bdeco)
                .addGap(139, 139, 139))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attribute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ca)
                    .addComponent(cfd)
                    .addComponent(Submit))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sk)
                    .addComponent(jButton3)
                    .addComponent(check2)
                    .addComponent(check3)
                    .addComponent(Deco2)
                    .addComponent(Deco3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ck)
                    .addComponent(checkb)
                    .addComponent(bdeco))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caActionPerformed
        attribute.setText("");
    }//GEN-LAST:event_caActionPerformed

    private void cfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfdActionPerformed
        fds.setText("");
    }//GEN-LAST:event_cfdActionPerformed

    private void fdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fdsActionPerformed

    private void attributeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attributeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attributeActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        String att = attribute.getText();
        String fd = fds.getText();
        
    }//GEN-LAST:event_SubmitActionPerformed

    private void check3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check3ActionPerformed
                Font font1 = new Font("SansSerif", Font.BOLD, 18);
                space1.setFont(font1);
                space2.setFont(font1);
                space3.setFont(font1);
        
                String att = attribute.getText();
                String fd = fds.getText();
		Set<Attribute> attrs = Attribute.getSet(att);
		Set<FuncDep> FD = FuncDep.getSet(fd);
		boolean check = Algos.check3NF(attrs, FD).isEmpty();
                
                if (check == true)
                space2.setText("This relation is in 3NF ");
                else{
                    space2.setText("The relation is not in 3NF \n\n" + "FD's violating 3NF: \n" );
                    Set<FuncDep> name = Algos.check3NF(attrs, FD);
                    for(FuncDep sa : name){
                        String str = space2.getText() + sa;
			space2.setText(str + '\n');}
        }
        
    }//GEN-LAST:event_check3ActionPerformed

    private void checkbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbActionPerformed
        
                String att = attribute.getText();
                String fd = fds.getText();
                Font font1 = new Font("SansSerif", Font.BOLD, 18);
                space1.setFont(font1);
                space2.setFont(font1);
                space3.setFont(font1);
        
                
		Set<Attribute> attrs = Attribute.getSet(att);
		Set<FuncDep> FD = FuncDep.getSet(fd);
                boolean check = Algos.checkBCNF(attrs, FD).isEmpty();
		
                   if (check == true)
        space2.setText("This relation is in BCNF ");
        else{
            space2.setText("The relation is not in BCNF \n\n" + "FD's violating BCNF: \n" );
            Set<FuncDep> name = Algos.checkBCNF(attrs, FD);
            for(FuncDep sa : name){
                        String str = space2.getText() + sa;
			space2.setText(str + '\n');}
        }
	
    }//GEN-LAST:event_checkbActionPerformed

    private void ckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckActionPerformed
                
                Font font1 = new Font("SansSerif", Font.BOLD, 18);
                space1.setFont(font1);
                space2.setFont(font1);
                space3.setFont(font1);
                space1.setText(" ");
                space1.setText("All Candidate Keys are : \n \n");
                String att = attribute.getText();
                String fd = fds.getText();
                
                Set<FuncDep> FD = FuncDep.getSet(fd);
		Set<Attribute> attrs = Attribute.getSet(att);
		
                
		Set<Set<Attribute>> keys = Algos.keys(attrs, FD);
		for(Set<Attribute> sa : keys){
                        String str = space1.getText() + sa;
			space1.setText(str + '\n');
		
		}
    }//GEN-LAST:event_ckActionPerformed

    private void skActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skActionPerformed
             Font font1 = new Font("SansSerif", Font.BOLD, 18);
        space1.setFont(font1);
        space2.setFont(font1);
        space3.setFont(font1);
        space1.setText(" ");
        space1.setText("All Super Keys are : \n \n");
                String att = attribute.getText();
        String fd = fds.getText();

        Set<FuncDep> FD = FuncDep.getSet(fd);
        Set<Attribute> attrs = Attribute.getSet(att);

        Set<Set<Attribute>> keys = Algos.superKeys(attrs, FD);
        for(Set<Attribute> sa : keys)
        {
            String str = space1.getText() + sa;
            space1.setText(str +'\n');
        }
    }//GEN-LAST:event_skActionPerformed

    private void bdecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdecoActionPerformed
                String att = attribute.getText();
                String fd = fds.getText();
                Set<Attribute> attrs = Attribute.getSet(att);
                Set<FuncDep> FD = FuncDep.getSet(fd);
                boolean check = Algos.checkBCNF(attrs, FD).isEmpty();
                Font font1 = new Font("SansSerif", Font.BOLD, 18);
                space3.setFont(font1);
                if (check == true){
                    space3.setText("No decomposition required.\nRelation already is in BCNF.");
                }
                else{
                Relation original = new Relation(attrs, FD);
		
		Set<Relation> decomposed = original.decomposeToBCNF();
		space3.setText("The suggested decomposition to BCNF is :\nTake the following FDs into another relation :\n\n");
		for(Relation r : decomposed){
			String str = space3.getText() + r;
                        space3.setText(str +" \n \n" );
                        
		}
                String str = space3.getText();
                space3.setText(str + "\n" + "LHS is key in each new Relation");}
    }//GEN-LAST:event_bdecoActionPerformed

    private void check2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check2ActionPerformed
        String att = attribute.getText();
        String fd = fds.getText();
        
        Font font1 = new Font("SansSerif", Font.BOLD, 18);
        space1.setFont(font1);
        space2.setFont(font1);
        space3.setFont(font1);
        
        Set<Attribute> attrs = Attribute.getSet(att);
        Set<FuncDep> FD = FuncDep.getSet(fd);
        boolean check = Algos.check2NF(attrs, FD).isEmpty();

        if (check == true)
        space2.setText("This relation is in 2NF ");
        else{
            space2.setText("The relation is not in 2NF. It is in 1NF.\n\n" + "FD's violating 2NF: \n" );
            Set<FuncDep> name = Algos.check2NF(attrs, FD);
            for(FuncDep sa : name){
                        String str = space2.getText() + sa;
			space2.setText(str + '\n');}
        }
        
    }//GEN-LAST:event_check2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
		Font font1 = new Font("SansSerif", Font.BOLD, 18);
                space1.setFont(font1);
                String att = attribute.getText();
                String fd = fds.getText();
                space1.setText(" ");
                Set<FuncDep> FD = FuncDep.getSet(fd);
		Set<Attribute> attrs = Attribute.getSet(att);
                space1.setText("Closure of the relation is : \n \n");
                String str = space1.getText();
		space1.setText(str+ Algos.closure(attrs, FD).toString());
	
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Deco3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deco3ActionPerformed
        String att = attribute.getText();
        String fd = fds.getText();
        Set<Attribute> attrs = Attribute.getSet(att);
        Set<FuncDep> FD = FuncDep.getSet(fd);
        boolean check = Algos.check3NF(attrs, FD).isEmpty();
        Font font1 = new Font("SansSerif", Font.BOLD, 18);
                space3.setFont(font1);
        if(check == true)
            space3.setText("No decomposition required.\nRelation already is in 3NF.");
        else{
       
        Relation original = new Relation(attrs, FD);

        Set<Relation> decomposed = original.decomposeTo3NF();

        space3.setText("The suggested decomposition to 3NF is:\nTake the following FDs into another relation :\n\n");
        for(Relation r : decomposed){
            String str = space3.getText() + r;
            space3.setText(str +'\n'+'\n');
    	}
        String str = space3.getText();
        space3.setText(str + "\n" + "LHS is key in each new Relation");}
    }//GEN-LAST:event_Deco3ActionPerformed

    private void Deco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deco2ActionPerformed

        String att = attribute.getText();
        String fd = fds.getText();
        Set<Attribute> attrs = Attribute.getSet(att);
        Set<FuncDep> FD = FuncDep.getSet(fd);
        Font font1 = new Font("SansSerif", Font.BOLD, 18);
                space3.setFont(font1);
        boolean check = Algos.check2NF(attrs, FD).isEmpty();
        if (check ==true){
            space3.setText("No need for decomposition.\nRelation is already in 2NF.");
        }
        else
        {
        Relation original = new Relation(attrs, FD);

        Set<Relation> decomposed = original.decomposeTo2NF();

        space3.setText("The suggested decomposition to 2NF is :\nTake the following FDs into another relation :\n \n");
        for(Relation r : decomposed){
            String str = space3.getText() + r;
            space3.setText(str +'\n'+ '\n');
        }
        String str = space3.getText();
        space3.setText(str + "\n" + "LHS is key in each new Relation");
    }//GEN-LAST:event_Deco2ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Front().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deco2;
    private javax.swing.JButton Deco3;
    private javax.swing.JButton Submit;
    private javax.swing.JTextField attribute;
    private javax.swing.JButton bdeco;
    private javax.swing.JButton ca;
    private javax.swing.JButton cfd;
    private javax.swing.JButton check2;
    private javax.swing.JButton check3;
    private javax.swing.JButton checkb;
    private javax.swing.JButton ck;
    private javax.swing.JLabel fd;
    private javax.swing.JTextField fds;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton sk;
    private javax.swing.JTextArea space1;
    private javax.swing.JTextArea space2;
    private javax.swing.JTextArea space3;
    // End of variables declaration//GEN-END:variables
}
